title: 16n
description: a bank of sixteen faders
plugins:
  - jekyll-seo-tag
exclude:
  - README.md
  - update_editor.sh
include:
  - _*.js
  - _*.css
github:
  is_project_page: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
